name: Docker CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'docker-compose.yml'
      - 'Dockerfile'
      - '**/Dockerfile'
      - '.docker/**'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'docker-compose.yml'
      - 'Dockerfile'
      - '**/Dockerfile'
      - '.docker/**'
      - '.github/workflows/docker.yml'

jobs:
  build:
    name: Build and Test Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker images
        run: docker-compose build
      
      - name: Start Docker containers
        run: docker-compose up -d
      
      - name: Wait for containers to be ready
        run: |
          echo "Waiting for containers to be ready..."
          sleep 30
      
      - name: Check container status
        run: docker-compose ps
      
      - name: Test backend health endpoint
        run: |
          curl -f http://localhost:8080/health || exit 1
          echo "Backend health check passed"
      
      - name: Test frontend
        run: |
          curl -f http://localhost || exit 1
          echo "Frontend check passed"
      
      - name: View logs if tests fail
        if: failure()
        run: docker-compose logs
      
      - name: Stop containers
        if: always()
        run: docker-compose down
